name: Sample-Failure-Tag

on:
  pull_request:

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # works
      - uses: github/codeql-action/init@4238421316c33d73aeea2801274dd286f157c2bb

      # doesnt work
      #- uses: ncipollo/release-action@v1.8.10