name: Sample-Failure-Tag

on:
  pull_request:

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # works
      - uses: github/codeql-action/init@883476649888a9e8e219d5b2e6b789dc024f690c

      # doesnt work
      #- uses: ncipollo/release-action@v1.8.10