name: Sample-Failure-Tag

on:
  pull_request:

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # works
      - uses: github/codeql-action/init@41a4ada31ba866a7f1196b9602703a89edd69e22

      # doesnt work
      #- uses: ncipollo/release-action@v1.8.10