name: Sample-Failure-Tag

on:
  pull_request:

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # works
      - uses: github/codeql-action/init@2f58583a1b24a7d3c7034f6bf9fa506d23b1183b

      # doesnt work
      #- uses: ncipollo/release-action@v1.8.10