name: Sample-Failure-Tag

on:
  pull_request:

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # works
      - uses: github/codeql-action/init@86f3159a697a097a813ad9bfa0002412d97690a4

      # doesnt work
      #- uses: ncipollo/release-action@v1.8.10