name: Sample-Failure-Tag

on:
  pull_request:

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # works
      - uses: github/codeql-action/init@f5d822707ee6e8fb81b04a5c0040b736da22e587

      # doesnt work
      #- uses: ncipollo/release-action@v1.8.10