name: Sample-Failure-Hash

on:
  pull_request:

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0

      - uses: ncipollo/release-action@3e88dac4cfd56ac692e06becafa84464a56e3286