name: Sample-Failure-Hash

on:
  pull_request:

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: ncipollo/release-action@215101a6e62db34b334af623ab3a43e27baa93d9