name: Sample-Failure-Tag

on:
  pull_request:

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # works
      - uses: github/codeql-action/init@0182a2c78c8a55b763909348834ed54d735ab3e2

      # doesnt work
      #- uses: ncipollo/release-action@v1.8.10