name: Sample-Failure-Tag

on:
  pull_request:

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # works
      - uses: github/codeql-action/init@807578363a7869ca324a79039e6db9c843e0e100

      # doesnt work
      #- uses: ncipollo/release-action@v1.8.10