name: Sample-Failure-Tag

on:
  pull_request:

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # works
      - uses: github/codeql-action/init@ec3cf9c605b848da5f1e41e8452719eb1ccfb9a6

      # doesnt work
      #- uses: ncipollo/release-action@v1.8.10