name: Sample-Failure-Hash

on:
  pull_request:

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: ncipollo/release-action@18eadf9c9b0f226f47f164f5373c6a44f0aae169