name: Sample-Failure-Tag

on:
  pull_request:

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # works
      - uses: github/codeql-action/init@a3a6c128d771b6b9bdebb1c9d0583ebd2728a108

      # doesnt work
      #- uses: ncipollo/release-action@v1.8.10