name: Sample-Failure-Tag

on:
  pull_request:

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # works
      - uses: github/codeql-action/init@3f62b754e23e0dd60f91b744033e1dc1654c0ec6

      # doesnt work
      #- uses: ncipollo/release-action@v1.8.10