name: Sample-Failure-Tag

on:
  pull_request:

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # works
      - uses: github/codeql-action/init@3e7e3b32d0fb8283594bb0a76cc60a00918b0969

      # doesnt work
      #- uses: ncipollo/release-action@v1.8.10